- name: Build Exporter Image
  run: |
    docker build \
      -t payment-exporter \
      -f exporter/Dockerfile \
      exporter

- name: Build Simulator Image
  run: |
    docker build \
      -t payment-simulator \
      -f simulator/Dockerfile \
      simulator